### ISSUE TITLE
Badges with year and region

### ISSUE THREAD

**Issue by Chan9390** [toolswatch/badges#1]
I think it would be better if you can create badges with the year and region too. Some tools which has made it to different arsenal events in the same year find it hard to mention in it near badges. Doing it manually ends up making readme bit clumsy.

![screenshot-2017-11-9 datasploit datasploit](https://user-images.githubusercontent.com/12944530/32589856-0463a304-c53d-11e7-8d8c-e4892c5c1c19.png)

**Comment by toolswatch** [comment]
Good idea.
Will do !!

**Comment by Chan9390** [comment]
Hey @toolswatch Any updates ?
