### ISSUE TITLE
2020-2022 BH Arsenal badges have not been created

### ISSUE THREAD

**Issue by hitenkoku** [toolswatch/badges#14]
The following Black Hat 2020-2022 badges have not been created.
 
 - 2020
   - BH Asia Arsenal
   - BH USA Arsenal
   - BH Europe Arsenal
 - 2021
   - BH Asia Arsenal
   - BH USA Arsenal
   - BH Europe Arsenal (this badge is pull requested #11 / #13  )
- 2022(prepare)
   - BH Asia Arsenal
   - BH Europe Arsenal
   - BH USA Arsenal

**Comment by toolswatch** [comment]
Awesome bro .. Thanks a lot :) 
Much appreciated

**Comment by hitenkoku** [comment]
@toolswatch  I  did pull request #15  for the 2020-2022 badges add.
Would you check it?
