### ISSUE TITLE
Request for BlackHat 2023 badge

### ISSUE THREAD

**Issue by rbeede** [toolswatch/badges#19]
Can the svg be generated for BlackHat 2023 please?

**Comment by oliviagallucci** [comment]
^ I second this :)

**Comment by oliviagallucci** [comment]
`[![Arsenal](https://github.com/toolswatch/badges/blob/master/arsenal/usa/2023.svg)](https://www.toolswatch.org/2015/06/black-hat-arsenal-usa-2015-speakers-lineup/)`

^ this creates the badge, but I think there needs to be an updated link. 

Right, @toolswatch? 

Thanks!
