### ISSUE TITLE
Add BHUSA 2019 Badges

### ISSUE THREAD

**Issue by leonjza** [toolswatch/badges#8]
Hey,

Please may we have badges for Blackhat Arsenal 2019.

Thanks!

**Comment by cappetta** [comment]
Please add BHEU Arsenal 2019 to the list as well!

**Comment by cappetta** [comment]
Created PR for Europe, looks like USA & ASIA exist

https://github.com/toolswatch/badges/pull/10

**Comment by leonjza** [comment]
Ah thanks!
